# language: python
sudo: true
language: python

python: 3.6
os: "linux"

before_install:
  - pip install .

script:
- tox
- if [ $TRAVIS_BRANCH == "master" ]; then
    sbt docker:publishLocal;
    docker login -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY_URL;
    docker build -t soulshake/startup-threads-cli/nonexistent .
    docker images;
    docker push hub.docker.com/$DOCKER_REGISTRY_USERNAME/startup-threads-cli/nonexistent
  fi
