language: bash

script:
  - sleep 1

notifications:
  webhooks:
    urls:
      - http://soulshake.ngrok.io/services/travis/gwos
    on_success: change # default: always
    on_failure: always # default: always
    on_start: change   # default: never
    on_cancel: always # default: always
    on_error: always # default: always
