language: bash

sudo: required

dist: trusty

services:
  - docker

#python:
#- "2.7"
#- "3.6"

#before_install:
  #- ls -la /home
  #- pip install .

script:
  - ./check-dns-bits

notifications:
  slack:
    rooms:
      - travisci:6PKoW5khxrYKSYje7JIbd4yL
    on_success: change
    on_failure: change

before_script:
  - docker pull tutum/dnsutils
  - git config --global user.email "aj@soulshake.net"
  - git config --global user.name "Travis-CI"

after_script:
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - git commit --allow-empty "Empty commit from Travis"
  - git push origin master

after_failure:
  - date -u

after_success:
  - date -u
