language: python

python:
- 2.7
- 3.6

os:
- "linux"

git:
  lfs_skip_smudge: true

before_install:
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
  - git lfs pull
  - pip install .

script:
  - tox


after_success:
  - >-
      curl
      -H "Content-Type: application/json"
      --data '{"source_type": "Branch", "source_name": "master"}'
      -X POST "$DOCKER_HUB_TRIGGER_URL"
