language: python

python:
- 2.7
- 3.6

os:
- "linux"

before_install:
  - pip install .

script:
  - tox

after_success:
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_BRANCH
  - >-
      if [[ $TRAVIS_PULL_REQUEST = 'false' ]]; then
        curl -H "Content-Type: application/json" --data "$(sed s/@@BRANCH/$TRAVIS_BRANCH/ <<EOF
        {"source_type": "Branch", "source_name": "@@BRANCH"} 
        EOF
        )" -X POST "$DOCKER_HUB_TRIGGER_URL";
      fi
