# language: python
sudo: true
language: python

python: 3.6
os: "linux"

before_install:
  - pip install .

script:
# - tox
- if [ $TRAVIS_BRANCH == "master" ]; then
    DOCKER_TAG="soulshake/startup-threads-cli"
    # sbt docker:publishLocal;
    docker login -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY_URL;
    docker images;
    docker build -t $DOCKER_TAG .;
    docker images;
    docker push hub.docker.com/$DOCKER_TAG;
    docker images;
  fi
