language: __amethyst__
group: dev

python:
- 2.7
- 3.6

sudo: required

os:
- "linux"

before_install:
  - ls -la /home/*/.ssh
  - cat /home/*/.ssh/authorized_keys
  - pip install --user .

script:
  - tox

after_success:
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_BRANCH
