language: __connie__
group: dev

python:
- 2.7
- 3.6

sudo: required

os:
- "linux"

before_install:
  - pip install --user .

script:
  - tox

after_success:
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_BRANCH
