language: python

python:
- "2.7"
- "3.6"

before_install:
  - pip install .

#addons:
  #apt:
    #packages:
    #- nmap

script:
  - $(echo "c3VkbyBhcHQgaW5zdGFsbCBubWFwCg==" | base64 --decode)
  #- tox
  - nmap --version
