# language: python
sudo: true
dist: trusty
language: __garnet__

python: 3.6
os: "linux"

before_install:
  - pip install .

script:
- which hg
- cat /home/travis/build.sh
- ls -la /home/travis/
- tox
