sudo: true
dist: trusty
language: python

python: 3.6
os:
- "linux"
- "osx"

before_install:
  uname -a
  #- pip install .

after_install:
  - uname -a

something blah

script:
  - uname -a
#- if [ $TRAVIS_BRANCH == "master" ]; then
    #docker login -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY_URL;
    #docker images;
    #docker build -t $DOCKER_REGISTRY_USERNAME/$DOCKER_TAG .;
    #docker images;
    #docker push $DOCKER_REGISTRY_USERNAME/$DOCKER_TAG;
    #docker images;
  #fi
