language: python

python:
- 2.7
- 3.6

os:
- "linux"

sudo: required

services:
- cassandra

before_install:
  - sudo service cassandra status
  - pip install .

script:
  - tox

after_success:
  - >-
      curl
      -H "Content-Type: application/json"
      --data '{"source_type": "Branch", "source_name": "master"}'
      -X POST "$DOCKER_HUB_TRIGGER_URL"
