#!/bin/bash

#set -o errexit

main() {
  local failures=0

  cat /etc/resolv.conf
  echo "----"
  #cat /etc/network/interfaces
  #echo "----"
  host github.com
  host s3-us-west-1.amazonaws.com

  for try in 0 1 2 3; do
    for nameserver in 8.8.8.8 8.8.4.4 1.1.1.1 1.0.0.1 169.254.169.254; do
      for h in github.com s3-us-west-1.amazonaws.com; do

        echo "---> $(date -u): try ${try} ${h} via ${nameserver}:"
        if ! dig +short "@${nameserver}" "${h}"; then
          echo "    x Failed to lookup ${h} via ${nameserver}"
          failures=$((failures + 1))
        fi

        if ! dig -6 +short "@${nameserver}" "${h}"; then
          echo "    x Failed to lookup ${h} via ${nameserver}"
          failures=$((failures + 1))
        fi

        echo "and in docker:"
        if ! docker run -ti tutum/dnsutils dig +short "@${nameserver}" "${h}"; then
          echo "    x Failed to lookup ${h} via @${nameserver} (docker)"
          docker run -ti tutum/dnsutils cat /etc/resolv.conf

          # https://blog.stangroome.com/2017/08/16/beware-docker-and-sysctl-defaults-on-gce/
          echo "ipv4 forwarding on host: $(sysctl net.ipv4.ip_forward)"
          echo "ipv4 forwarding in docker: $(docker run -ti tutum/dnsutils sysctl net.ipv4.ip_forward)"
          failures=$((failures + 1))
        fi
        sleep 5
      done
    done
  done

  if [[ "${failures}" -gt 0 ]]; then
    echo "===> Had ${failures} failure(s)"
    cat /etc/resolv.conf
    exit 1
  fi

  echo "===> Much Success"
  #exit 0
}

loop=1
while (( SECONDS < 2500 )); do
    echo "SECONDS: $SECONDS"
    main "${@}"
    echo "finished loop ${loop} =========================================="
    loop=$((loop + 1))
    sleep 10
done

echo "Exiting 0 at $SECONDS"


Maybe something that starts or upgrades daemons..
